source 'http://rubygems.org'

gem 'rails'
gem 'rake','0.8.7'

gem 'rspec-rails'
gem 'watir-webdriver-rails'

group :active_record do
	gem 'sqlite3'
end

group :mongoid do
	gem 'mongoid'
	gem 'bson_ext'
end


